source("https://bioconductor.org/biocLite.R")
install.packages("reshape2", repos='http://cran.us.r-project.org')
install.packages("ggplot2", repos='http://cran.us.r-project.org')
biocLite("limma")
biocLite("org.Hs.eg.db")
biocLite("RCurl")
biocLite("genefilter")
biocLite("annotate")
biocLite("GSEABase")
biocLite("geneplotter")
biocLite("GSVA")
biocLite("fgsea")
